### PR TITLE
Allow for 'tns' platform specific files

### PR DESCRIPTION
**Pull request by joshcomley**
See https://github.com/NativeScript/nativescript-vscode-extension/issues/252

Allowing for debugging platform specific files at the higher ".tns.[ext]" level.

### CODE REVIEW

**Comment by joshcomley** [comment]
@cla-bot check

**Comment by joshcomley** [comment]
Please can somebody review this - my plugin just updated automatically from my own version and it broke debugging in multi-environment projects.

**Comment by Fatme** [comment]
Hey @joshcomley,

Really sorry for the late reply!

We've reviewed your code and it seems your application is with legacy code-shared structure. If this is the case, you can follow [the steps described here in order to migrate to the new structure](https://github.com/NativeScript/nativescript-schematics/issues/254).  So, no additional logic will be needed in `vscode-extension`.

However, the fix seems safe so I'll merge the PR.

**Comment by joshcomley** [comment]
@Fatme Thanks for the update! Is there an updated sample project with the new structure somewhere I can reference? Ideally Angular etc.

**Comment by Fatme** [comment]
@joshcomley,

Yep, we have an updated project [here](https://github.com/NativeScript/north-star). Reviewing the history of the repo, you can see how it is migrated. Maybe the most interesting commits are the following:
* https://github.com/NativeScript/north-star/commit/fc422e93f2ad5dd007a15e833d3be32e7c673aa1 - All relative imports are updated to start with `@src` symbol
* https://github.com/NativeScript/north-star/commit/3ce77d9fca7c13cf445fcbeb527bc9298f91b3c8 -  The required changes are applied into `tsconfig` files
* https://github.com/NativeScript/north-star/commit/d8a17b690a249636ce94c40bebd149233ed328c0v - `@nativescript/tslint-rules` package is added.

**Comment by joshcomley** [comment]
@Fatme thank you so much, I will have a look through all that

**Pull request merged**
